# Generated by Django 5.2.1 on 2025-05-26 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['warehouse__name', 'product__name'], 'verbose_name': 'Inventar', 'verbose_name_plural': 'Inventarlar'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Ombor', 'verbose_name_plural': 'Omborlar'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='capacity',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='capacity_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Sig'imi (kv.m)"),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Mas'ul shaxs"),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse', verbose_name='Ombor'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ombor nomi'),
        ),
    ]
