# Generated by Django 5.2.1 on 2025-05-27 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0002_alter_inventory_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('in_date', models.DateTimeField(auto_now_add=True, verbose_name='Kirim sanasi')),
                ('reason', models.CharField(blank=True, help_text='Kirim sababi (masalan: Yetkazib beruvchidan qabul)', max_length=255, null=True, verbose_name='Sabab')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='warehouses.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
                'ordering': ['-in_date'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('out_date', models.DateTimeField(auto_now_add=True, verbose_name='Chiqim sanasi')),
                ('reason', models.CharField(blank=True, help_text='Chiqim sababi (masalan: Mijozga sotildi, qaytarildi)', max_length=255, null=True, verbose_name='Sabab')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='warehouses.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
                'ordering': ['-out_date'],
            },
        ),
    ]
